---
- name: open http and https services
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https

- name: open tcp port 8080 and 8443
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - "8080/tcp"
    - "8443/tcp"

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded 
  notify:
    Restart Services

