---
- name: Install pymysql
  pip:
    name: pymysql
    state: present

- name: Start and Enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: true
    
- name: Set root password for mariadb
  mysql_user:
    name: root
    login_user: root
    login_password: ""
    login_host: "{{ MYSQL_HOSTNAME }}"
    password: "{{ DB_PASSWD }}"
    state: present
  ignore_errors: true   # PASSWORD ALREADY SET

- name: Delete Anonymous Users {{ MYSQL_HOSTNAME }}
  mysql_user:
    name: ""
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    host: "{{ MYSQL_HOSTNAME }}"
    state: absent

- name: Remove test database
  mysql_db:
    db: test
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    state: absent

# TODO: CLEANUP - USE MYSQL MODULE

- name: Create {{ DB_NAME }} Database
  mysql_db:
    name: "{{ DB_NAME }}"
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    state: present

- name: Grant User access to Database
  mysql_user:
    name: "{{ DB_USER }}"
    password: "{{ DB_PASSWD }}"
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    priv: "{{ DB_NAME }}.*:ALL,GRANT"
    state: present

- name: Import Database
  mysql_db:
    name: "{{ DB_NAME }}"
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    state: import
    target: "{{ INSTALL_DIR }}extension/mysql/schema/{{ item }}.sql"
  ignore_errors: true    # Database already contains info
  loop:
    - 001-create-schema
    - 002-create-admin-user

- name: Insert timezone info into mysql database
  shell: "/usr/bin/mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p{{ DB_PASSWD }}"
  args:
    warn: no

- name: Get Timezone Info
  shell:  "timedatectl | grep 'Time zone:' | awk '{ print $3 }'"
  args:
    warn: no
  register: timezone

- name: Insert {{ timezone.stdout }} into /etc/my.cnf
  lineinfile:
    path: /etc/my.cnf
    insertafter: "^\\[mysqld\\]"
    line: "default-time-zone={{ timezone.stdout }}"
   
- name: Restart mariadb service
  service:
    name: mariadb
    state: restarted

