---
- name: Backup nginx default configuration
  copy:
    src: /etc/nginx/conf.d/default.conf
    dest: /etc/nginx/conf.d/default.conf.orig
  failed_when: false

- name: Generate nginx conf file
  template:
    src: guacamole.conf.j2
    dest: /etc/nginx/conf.d/guacamole.conf

#- name: Generate nginx ssl conf file
#  template:
#    src: guacamole_ssl.conf.j2
#    dest: /etc/nginx/conf.d/guacamole_ssl.conf

- name: chmod all nginx directories 750 
  command: find /etc/nginx -type d -exec chmod 750 {} \;
    
- name: chmod all nginx files to 644
  command: find /etc/nginx -type f -exec chmod 644 {} \;

- name: Replace default nginx html pages with blank html pages
  template:
    src: blank.html.j2
    dest: "{{ item }}"
  loop:
    - /usr/share/nginx/html/index.html
    - /usr/share/nginx/html/50x.html

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: true

